declare const styles: {
  readonly "overlay": string;
  readonly "dialog": string;
  readonly 'dialogSmallScreen': string;
  readonly "dialogBody": string;
  readonly "content": string;
  readonly "loading": string;
  readonly "error": string;
  readonly "type-inline": string;
  readonly "type-image": string;
  readonly "entranceOverlay": string;
  readonly "entrancePanel": string;
  readonly "-isType-inline": string;
  readonly "entranceContent": string;
  readonly "exitOverlay": string;
  readonly "complete": string;
  readonly "title": string;
  readonly "entrancePanel_small": string;
};
export = styles;
